export const API_CONFIG = {
  BASE_URL: 'https://manufiq.onrender.com',
  TIMEOUT: 30000,
  ENDPOINTS: {
    AUTH: {
      REGISTER: '/api/auth/register',
      LOGIN: '/api/auth/login',
      LOGOUT: '/api/auth/logout',
      REFRESH: '/api/auth/refresh',
      VERIFY_EMAIL: '/api/auth/verify-email',
      FORGOT_PASSWORD: '/api/auth/forgot-password',
      RESET_PASSWORD: '/api/auth/reset-password',
      CHANGE_PASSWORD: '/api/auth/change-password',
    },
     ITEMS: {
      LIST: '/api/materials',
      CREATE: '/api/materials',
      GET: (id: string) => `/api/materials/${id}`,
      UPDATE: (id: string) => `/api/materials/${id}`,
      ADJUST: (id: string) => `/api/materials/${id}/adjust`,
      EVENTS: (id: string) => `/api/materials/${id}/events`,
    },
    BUSINESS: {
      GET: (id: string) => `/api/business/${id}`,
      UPDATE: (id: string) => `/api/business/${id}`,
      UPLOAD_DOC: (id: string) => `/api/business/${id}/doc`,
      SETTINGS: (id: string) => `/api/business/${id}/settings`,
    },
    SYNC: {
      PUSH: '/api/sync/push',
      PULL: '/api/sync/pull',
      CONFLICTS: '/api/sync/conflicts',
      STATUS: '/api/sync/status',
      DEDUPLICATE: '/api/sync/deduplicate',
      CLEANUP: '/api/sync/cleanup',
    },
    DEVICES: {
      REGISTER: '/api/devices/register',
    },
    NOTIFICATIONS: {
      LIST: '/api/notifications',
      UNREAD_COUNT: '/api/notifications/unread-count',
      MARK_READ: (id: string) => `/api/notifications/${id}/read`,
      MARK_ALL_READ: '/api/notifications/read-all',
      DELETE: (id: string) => `/api/notifications/${id}`,
    },
    ALERTS: {
      LIST: '/api/alerts',
      RESOLVE: (id: string) => `/api/alerts/${id}/resolve`,
      CHECK: '/api/alerts/check',
    },
     REPORTS: {
      SUMMARY: '/api/reports/summary',
      MATERIAL_USAGE: '/api/reports/material-usage',
      TEAM_PRODUCTIVITY: '/api/reports/team-productivity',
      PRODUCTION_TRENDS: '/api/reports/production-trends',
      EXPORT_PDF: '/api/reports/export/pdf',
      EXPORT_CSV: '/api/reports/export/csv',
      HISTORICAL: '/api/reports/historical',      
    },
    ORDERS: {
      CREATE : '/api/orders',
      LIST : '/api/orders',
      STATS : '/api/orders/stats',
      GET : (id: string) => `/api/orders/${id}`,
      UPDATE : (id: string) => `/api/orders/${id}`,
      UPDATE_STATUS : (id: string) => `/api/orders/${id}/status`,
      ASSIGN_STAFF : (id: string) => `/api/orders/${id}/assign`,
      CANCEL : (id: string) => `/api/orders/${id}/cancel`,
      HISTORY : (id: string) => `/api/orders/${id}/history`,
  },
  PROGRESS: {
    ADD_STEPS: (orderId: string) => `/api/progress/${orderId}/steps`,
    GET_STEPS: (orderId: string) => `/api/progress/${orderId}/steps`,
    UPDATE_STEP: (stepId: string) => `/api/progress/steps/${stepId}`,
    DELETE_STEP: (stepId: string) => `/api/progress/steps/${stepId}`,
    MARK_DELIVERED: (orderId: string) => `/api/progress/${orderId}/deliver`,
    GET_RECEIPT: (orderId: string) => `/api/progress/${orderId}/receipt`,
    LIST_RECEIPTS: '/api/progress/receipts',
  },
  }
};
